//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RECHARGEDUNIYA.SRService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.inoutrecharge.com/", ConfigurationName="SRService.SRServiceSoap")]
    public interface SRServiceSoap {
        
        // CODEGEN: Generating message contract since message DoRechargeRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inoutrecharge.com/DoRecharge", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RECHARGEDUNIYA.SRService.DoRechargeResponse DoRecharge(RECHARGEDUNIYA.SRService.DoRechargeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inoutrecharge.com/DoRecharge", ReplyAction="*")]
        System.Threading.Tasks.Task<RECHARGEDUNIYA.SRService.DoRechargeResponse> DoRechargeAsync(RECHARGEDUNIYA.SRService.DoRechargeRequest request);
        
        // CODEGEN: Generating message contract since message CheckStatusRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inoutrecharge.com/CheckStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RECHARGEDUNIYA.SRService.CheckStatusResponse CheckStatus(RECHARGEDUNIYA.SRService.CheckStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inoutrecharge.com/CheckStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<RECHARGEDUNIYA.SRService.CheckStatusResponse> CheckStatusAsync(RECHARGEDUNIYA.SRService.CheckStatusRequest request);
        
        // CODEGEN: Generating message contract since message MyBalanceRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inoutrecharge.com/MyBalance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RECHARGEDUNIYA.SRService.MyBalanceResponse MyBalance(RECHARGEDUNIYA.SRService.MyBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inoutrecharge.com/MyBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<RECHARGEDUNIYA.SRService.MyBalanceResponse> MyBalanceAsync(RECHARGEDUNIYA.SRService.MyBalanceRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.inoutrecharge.com/")]
    public partial class Information : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Credentials apiCredentialsField;
        
        private string mobileToRechargeField;
        
        private string billerAccountNumberField;
        
        private string aPIAccountRefField;
        
        private decimal amountField;
        
        private byte rechargeViaField;
        
        private byte typeOfRechargeField;
        
        private int serviceCodeField;
        
        private int operatorCodeField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Credentials ApiCredentials {
            get {
                return this.apiCredentialsField;
            }
            set {
                this.apiCredentialsField = value;
                this.RaisePropertyChanged("ApiCredentials");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MobileToRecharge {
            get {
                return this.mobileToRechargeField;
            }
            set {
                this.mobileToRechargeField = value;
                this.RaisePropertyChanged("MobileToRecharge");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BillerAccountNumber {
            get {
                return this.billerAccountNumberField;
            }
            set {
                this.billerAccountNumberField = value;
                this.RaisePropertyChanged("BillerAccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string APIAccountRef {
            get {
                return this.aPIAccountRefField;
            }
            set {
                this.aPIAccountRefField = value;
                this.RaisePropertyChanged("APIAccountRef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public byte RechargeVia {
            get {
                return this.rechargeViaField;
            }
            set {
                this.rechargeViaField = value;
                this.RaisePropertyChanged("RechargeVia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public byte TypeOfRecharge {
            get {
                return this.typeOfRechargeField;
            }
            set {
                this.typeOfRechargeField = value;
                this.RaisePropertyChanged("TypeOfRecharge");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int ServiceCode {
            get {
                return this.serviceCodeField;
            }
            set {
                this.serviceCodeField = value;
                this.RaisePropertyChanged("ServiceCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int OperatorCode {
            get {
                return this.operatorCodeField;
            }
            set {
                this.operatorCodeField = value;
                this.RaisePropertyChanged("OperatorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.inoutrecharge.com/")]
    public partial class Credentials : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        private string deviceIDField;
        
        private string newPasswordField;
        
        private string fromDateField;
        
        private string toDateField;
        
        private int operatingSystemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DeviceID {
            get {
                return this.deviceIDField;
            }
            set {
                this.deviceIDField = value;
                this.RaisePropertyChanged("DeviceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NewPassword {
            get {
                return this.newPasswordField;
            }
            set {
                this.newPasswordField = value;
                this.RaisePropertyChanged("NewPassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string FromDate {
            get {
                return this.fromDateField;
            }
            set {
                this.fromDateField = value;
                this.RaisePropertyChanged("FromDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ToDate {
            get {
                return this.toDateField;
            }
            set {
                this.toDateField = value;
                this.RaisePropertyChanged("ToDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int OperatingSystem {
            get {
                return this.operatingSystemField;
            }
            set {
                this.operatingSystemField = value;
                this.RaisePropertyChanged("OperatingSystem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DoRecharge", WrapperNamespace="http://www.inoutrecharge.com/", IsWrapped=true)]
    public partial class DoRechargeRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.inoutrecharge.com/")]
        public RECHARGEDUNIYA.SRService.Information Information;
        
        public DoRechargeRequest() {
        }
        
        public DoRechargeRequest(RECHARGEDUNIYA.SRService.Information Information) {
            this.Information = Information;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DoRechargeResponse", WrapperNamespace="http://www.inoutrecharge.com/", IsWrapped=true)]
    public partial class DoRechargeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.inoutrecharge.com/", Order=0)]
        public string DoRechargeResult;
        
        public DoRechargeResponse() {
        }
        
        public DoRechargeResponse(string DoRechargeResult) {
            this.DoRechargeResult = DoRechargeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckStatus", WrapperNamespace="http://www.inoutrecharge.com/", IsWrapped=true)]
    public partial class CheckStatusRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.inoutrecharge.com/")]
        public RECHARGEDUNIYA.SRService.Information Information;
        
        public CheckStatusRequest() {
        }
        
        public CheckStatusRequest(RECHARGEDUNIYA.SRService.Information Information) {
            this.Information = Information;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckStatusResponse", WrapperNamespace="http://www.inoutrecharge.com/", IsWrapped=true)]
    public partial class CheckStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.inoutrecharge.com/", Order=0)]
        public string CheckStatusResult;
        
        public CheckStatusResponse() {
        }
        
        public CheckStatusResponse(string CheckStatusResult) {
            this.CheckStatusResult = CheckStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MyBalance", WrapperNamespace="http://www.inoutrecharge.com/", IsWrapped=true)]
    public partial class MyBalanceRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.inoutrecharge.com/")]
        public RECHARGEDUNIYA.SRService.Information Information;
        
        public MyBalanceRequest() {
        }
        
        public MyBalanceRequest(RECHARGEDUNIYA.SRService.Information Information) {
            this.Information = Information;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MyBalanceResponse", WrapperNamespace="http://www.inoutrecharge.com/", IsWrapped=true)]
    public partial class MyBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.inoutrecharge.com/", Order=0)]
        public string MyBalanceResult;
        
        public MyBalanceResponse() {
        }
        
        public MyBalanceResponse(string MyBalanceResult) {
            this.MyBalanceResult = MyBalanceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SRServiceSoapChannel : RECHARGEDUNIYA.SRService.SRServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SRServiceSoapClient : System.ServiceModel.ClientBase<RECHARGEDUNIYA.SRService.SRServiceSoap>, RECHARGEDUNIYA.SRService.SRServiceSoap {
        
        public SRServiceSoapClient() {
        }
        
        public SRServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SRServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SRServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SRServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RECHARGEDUNIYA.SRService.DoRechargeResponse RECHARGEDUNIYA.SRService.SRServiceSoap.DoRecharge(RECHARGEDUNIYA.SRService.DoRechargeRequest request) {
            return base.Channel.DoRecharge(request);
        }
        
        public string DoRecharge(RECHARGEDUNIYA.SRService.Information Information) {
            RECHARGEDUNIYA.SRService.DoRechargeRequest inValue = new RECHARGEDUNIYA.SRService.DoRechargeRequest();
            inValue.Information = Information;
            RECHARGEDUNIYA.SRService.DoRechargeResponse retVal = ((RECHARGEDUNIYA.SRService.SRServiceSoap)(this)).DoRecharge(inValue);
            return retVal.DoRechargeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RECHARGEDUNIYA.SRService.DoRechargeResponse> RECHARGEDUNIYA.SRService.SRServiceSoap.DoRechargeAsync(RECHARGEDUNIYA.SRService.DoRechargeRequest request) {
            return base.Channel.DoRechargeAsync(request);
        }
        
        public System.Threading.Tasks.Task<RECHARGEDUNIYA.SRService.DoRechargeResponse> DoRechargeAsync(RECHARGEDUNIYA.SRService.Information Information) {
            RECHARGEDUNIYA.SRService.DoRechargeRequest inValue = new RECHARGEDUNIYA.SRService.DoRechargeRequest();
            inValue.Information = Information;
            return ((RECHARGEDUNIYA.SRService.SRServiceSoap)(this)).DoRechargeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RECHARGEDUNIYA.SRService.CheckStatusResponse RECHARGEDUNIYA.SRService.SRServiceSoap.CheckStatus(RECHARGEDUNIYA.SRService.CheckStatusRequest request) {
            return base.Channel.CheckStatus(request);
        }
        
        public string CheckStatus(RECHARGEDUNIYA.SRService.Information Information) {
            RECHARGEDUNIYA.SRService.CheckStatusRequest inValue = new RECHARGEDUNIYA.SRService.CheckStatusRequest();
            inValue.Information = Information;
            RECHARGEDUNIYA.SRService.CheckStatusResponse retVal = ((RECHARGEDUNIYA.SRService.SRServiceSoap)(this)).CheckStatus(inValue);
            return retVal.CheckStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RECHARGEDUNIYA.SRService.CheckStatusResponse> RECHARGEDUNIYA.SRService.SRServiceSoap.CheckStatusAsync(RECHARGEDUNIYA.SRService.CheckStatusRequest request) {
            return base.Channel.CheckStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<RECHARGEDUNIYA.SRService.CheckStatusResponse> CheckStatusAsync(RECHARGEDUNIYA.SRService.Information Information) {
            RECHARGEDUNIYA.SRService.CheckStatusRequest inValue = new RECHARGEDUNIYA.SRService.CheckStatusRequest();
            inValue.Information = Information;
            return ((RECHARGEDUNIYA.SRService.SRServiceSoap)(this)).CheckStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RECHARGEDUNIYA.SRService.MyBalanceResponse RECHARGEDUNIYA.SRService.SRServiceSoap.MyBalance(RECHARGEDUNIYA.SRService.MyBalanceRequest request) {
            return base.Channel.MyBalance(request);
        }
        
        public string MyBalance(RECHARGEDUNIYA.SRService.Information Information) {
            RECHARGEDUNIYA.SRService.MyBalanceRequest inValue = new RECHARGEDUNIYA.SRService.MyBalanceRequest();
            inValue.Information = Information;
            RECHARGEDUNIYA.SRService.MyBalanceResponse retVal = ((RECHARGEDUNIYA.SRService.SRServiceSoap)(this)).MyBalance(inValue);
            return retVal.MyBalanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RECHARGEDUNIYA.SRService.MyBalanceResponse> RECHARGEDUNIYA.SRService.SRServiceSoap.MyBalanceAsync(RECHARGEDUNIYA.SRService.MyBalanceRequest request) {
            return base.Channel.MyBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<RECHARGEDUNIYA.SRService.MyBalanceResponse> MyBalanceAsync(RECHARGEDUNIYA.SRService.Information Information) {
            RECHARGEDUNIYA.SRService.MyBalanceRequest inValue = new RECHARGEDUNIYA.SRService.MyBalanceRequest();
            inValue.Information = Information;
            return ((RECHARGEDUNIYA.SRService.SRServiceSoap)(this)).MyBalanceAsync(inValue);
        }
    }
}
